[package]
name = "rustcast"
version = "0.1.0"
edition = "2024"

[dependencies]
pixels = "0.15"
winit = { version="0.29.15", features = ["wayland"] } 
glam = "0.30.5"
rand = { version ="0.9.2", features = ["small_rng"] }
rayon = "1.10"
